In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
Data_Path = r"D:\Projects\Smart_E-Commerce_Demand_&_Operations_Intelligence_System\01_Raw_Data"

customers = pd.read_csv(Data_Path + r"\olist_customers_dataset.csv")
geolocation = pd.read_csv(Data_Path + r"\olist_geolocation_dataset.csv")
order_items = pd.read_csv(Data_Path + r"\olist_order_items_dataset.csv")
payments = pd.read_csv(Data_Path + r"\olist_order_payments_dataset.csv")
reviews = pd.read_csv(Data_Path + r"\olist_order_reviews_dataset.csv")
orders = pd.read_csv(Data_Path + r"\olist_orders_dataset.csv")
products = pd.read_csv(Data_Path + r"\olist_products_dataset.csv")
sellers = pd.read_csv(Data_Path + r"\olist_sellers_dataset.csv")
category_translation = pd.read_csv(Data_Path + r"\product_category_name_translation.csv")

In [3]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "products": products,
    "sellers": sellers,
    "payments": payments,
    "reviews": reviews,
    "geolocation": geolocation,
    "category_translation": category_translation
}

for name, df in datasets.items():
    print(f"{name:20} -> {df.shape[0]:>7,} rows × {df.shape[1]:>2} columns")

customers            ->  99,441 rows ×  5 columns
orders               ->  99,441 rows ×  8 columns
order_items          -> 112,650 rows ×  7 columns
products             ->  32,951 rows ×  9 columns
sellers              ->   3,095 rows ×  4 columns
payments             -> 103,886 rows ×  5 columns
reviews              ->  99,224 rows ×  7 columns
geolocation          -> 1,000,163 rows ×  5 columns
category_translation ->      71 rows ×  2 columns

In [4]:
for name, df in datasets.items():
    print(f"\n{'=' * 60}")
    print(name.upper())
    print("=" * 60)
    print(list(df.columns))

============================================================
CUSTOMERS
============================================================
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

============================================================
ORDERS
============================================================
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

============================================================
ORDER_ITEMS
============================================================
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

============================================================
PRODUCTS
============================================================
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

============================================================
SELLERS
============================================================
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

============================================================
PAYMENTS
============================================================
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

============================================================
REVIEWS
============================================================
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

============================================================
GEOLOCATION
============================================================
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

============================================================
CATEGORY_TRANSLATION
============================================================
['product_category_name', 'product_category_name_english']

In [5]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB

In [6]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [7]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [8]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [9]:
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print(df.dtypes)

CUSTOMERS
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

ORDERS
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

ORDER_ITEMS
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

PRODUCTS
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

SELLERS
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

PAYMENTS
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

REVIEWS
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

GEOLOCATION
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

CATEGORY_TRANSLATION
product_category_name            str
product_category_name_english    str
dtype: object

In [10]:
for name, df in datasets.items():
    missing = df.isnull().sum()
    missing = missing[missing > 0].sort_values(ascending=False)

    print(f"\n{name.upper()}")

    if missing.empty:
        print("No missing values.")
    else:
        print(missing)

CUSTOMERS
No missing values.

ORDERS
order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
dtype: int64

ORDER_ITEMS
No missing values.

PRODUCTS
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

SELLERS
No missing values.

PAYMENTS
No missing values.

REVIEWS
review_comment_title      87656
review_comment_message    58247
dtype: int64

GEOLOCATION
No missing values.

CATEGORY_TRANSLATION
No missing values.

In [11]:
for name, df in datasets.items():
    duplicate_count = df.duplicated().sum()
    print(f"{name:20} -> {duplicate_count:,} duplicate rows")

customers            -> 0 duplicate rows
orders               -> 0 duplicate rows
order_items          -> 0 duplicate rows
products             -> 0 duplicate rows
sellers              -> 0 duplicate rows
payments             -> 0 duplicate rows
reviews              -> 0 duplicate rows
geolocation          -> 261,831 duplicate rows
category_translation -> 0 duplicate rows

In [12]:
id_columns = {
    "customers": ["customer_id", "customer_unique_id"],
    "orders": ["order_id", "customer_id"],
    "order_items": ["order_id", "order_item_id", "product_id", "seller_id"],
    "products": ["product_id"],
    "sellers": ["seller_id"],
    "payments": ["order_id", "payment_sequential"],
    "reviews": ["review_id", "order_id"],
    "category_translation": ["product_category_name"],
}

for dataset_name, columns in id_columns.items():
    df = datasets[dataset_name]

    print(f"\n{dataset_name.upper()}")

    for column in columns:
        if column in df.columns:
            print(f"{column:35} unique values: {df[column].nunique():,}")

CUSTOMERS
customer_id                         unique values: 99,441
customer_unique_id                  unique values: 96,096

ORDERS
order_id                            unique values: 99,441
customer_id                         unique values: 99,441

ORDER_ITEMS
order_id                            unique values: 98,666
order_item_id                       unique values: 21
product_id                          unique values: 32,951
seller_id                           unique values: 3,095

PRODUCTS
product_id                          unique values: 32,951

SELLERS
seller_id                           unique values: 3,095

PAYMENTS
order_id                            unique values: 99,440
payment_sequential                  unique values: 29

REVIEWS
review_id                           unique values: 98,410
order_id                            unique values: 98,673

CATEGORY_TRANSLATION
product_category_name               unique values: 71

In [13]:
orders["order_status"].value_counts(dropna=False)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [14]:
orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"],
    errors="coerce"
)

print("First order:", orders["order_purchase_timestamp"].min())
print("Last order :", orders["order_purchase_timestamp"].max())

First order: 2016-09-04 21:15:19
Last order : 2018-10-17 17:30:18

In [15]:
print("Orders:", orders["order_id"].nunique())
print("Order items:", order_items["order_id"].nunique())
print("Customers:", customers["customer_id"].nunique())
print("Products:", products["product_id"].nunique())
print("Sellers:", sellers["seller_id"].nunique())

Orders: 99441
Order items: 98666
Customers: 99441
Products: 32951
Sellers: 3095

In [16]:
order_customer_check = orders["customer_id"].isin(
    customers["customer_id"]
)
print(
    "Orders with valid customer_id:",
    f"{order_customer_check.mean() * 100:.2f}%"
)

#To check order_item
order_item_check = order_items["order_id"].isin(
    orders["order_id"]
)
print(
    "Order items with valid order_id:",
    f"{order_item_check.mean() * 100:.2f}%"
)

#To check product
product_check = order_items["product_id"].isin(
    products["product_id"]
)
print(
    "Order items with valid product_id:",
    f"{product_check.mean() * 100:.2f}%"
)

#To check seller
seller_check = order_items["seller_id"].isin(
    sellers["seller_id"]
)
print(
    "Order items with valid seller_id:",
    f"{seller_check.mean() * 100:.2f}%"
)

Orders with valid customer_id: 100.00%
Order items with valid order_id: 100.00%
Order items with valid product_id: 100.00%
Order items with valid seller_id: 100.00%

In [17]:
summary = []

for name, df in datasets.items():
    summary.append({
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "missing_cells": int(df.isnull().sum().sum()),
        "duplicate_rows": int(df.duplicated().sum())
    })

summary_df = pd.DataFrame(summary)

summary_df

                dataset     rows  columns  missing_cells  duplicate_rows
0             customers    99441        5              0               0
1                orders    99441        8           4908               0
2           order_items   112650        7              0               0
3              products    32951        9           2448               0
4               sellers     3095        4              0               0
5              payments   103886        5              0               0
6               reviews    99224        7         145903               0
7           geolocation  1000163        5              0          261831
8  category_translation       71        2              0               0

In [18]:
Data_Path = r"D:\Projects\Smart_E-Commerce_Demand_&_Operations_Intelligence_System\09_Outputs\tables/"

summary_df.to_csv(
    Data_Path + r"raw_dataset_summary.csv",
    index=False
)
print("raw dataset summary saved successfully.")

raw dataset summary saved successfully.